language: python
python:
  - "3.7"  # Или другая поддерживаемая версия Python

os: linux  # Travis CI работает на Linux

dist: xenial # Используйте xenial для совместимости

jdk: oraclejdk8 # Или более поздняя версия, если необходимо

env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.2
    - ANDROID_NDK_VERSION=21.4.7075529

cache:
  directories:
    - $HOME/.buildozer/android/platform/android-sdk
    - $HOME/.buildozer/android/dists

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git zip unzip
  - pip install --user virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install buildozer

install:
  - export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - mkdir -p $ANDROID_HOME
  - wget -O $ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
  - unzip $ANDROID_HOME/cmdline-tools.zip -d $ANDROID_HOME
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator
  - yes | sdkmanager --licenses || true # Принимаем все лицензии SDK
  - sdkmanager "platforms;android-$ANDROID_API" "build-tools;$ANDROID_BUILD_TOOLS"

script:
  - buildozer android debug

after_success:
  - ls bin  # Перечислим содержимое папки bin, чтобы убедиться, что APK создан
  # - Сюда можно добавить код для публикации APK (например, на GitHub Releases)